name: Deploy Client-Side (FTP)
on: push
jobs:
  client-ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: client
        run: npm ci
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_HEAD_TITLE: ${{ secrets.CLIENT_HEAD_TITLE }}
          envkey_TITLE: ${{ secrets.CLIENT_TITLE }}
          envkey_WS_SERVER_URL: ${{ secrets.CLIENT_WS_SERVER_URL }}
          envkey_CDN_UPLOAD_ENDPOINT: ${{ secrets.CLIENT_CDN_UPLOAD_ENDPOINT }}
          directory: client
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Build
        working-directory: client
        run: npm run build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          local-dir: client/dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
