name: Deploy Client-Side (FTP)
on: push
jobs:
  client-ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          local-dir: client/dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
