name: Deploy Server-Side (SSH)
on: push
jobs:
  server-ssh-deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v2.0
      #   with:
      #     envkey_PORT: ${{ secrets.SERVER_PORT }}
      #     envkey_CDN_URL: ${{ secrets.SERVER_CDN_URL }}
      #     envkey_CDN_LOCAL_PATH: ${{ secrets.SERVER_CDN_LOCAL_PATH }}
      #     envkey_CDN_MAX_FILE_SIZE: ${{ secrets.SERVER_CDN_MAX_FILE_SIZE }}
      #     directory: server
      #     file_name: .env
      #     fail_on_empty: false
      #     sort_keys: false

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          local-dir: server/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          username: ${{ secrets.FTP_USERNAME_SERVER }}
          password: ${{ secrets.FTP_PASSWORD_SERVER }}
          port: 21

      - name: Build in Server using SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          SERVER_PATH: ${{ secrets.SSH_SERVER_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: SERVER_PATH
          script: |
            cd $SERVER_PATH
            npm ci
            cp ../../.env ./.env
            pm2 restart chat-in-no-internet-server
